workflows:
  island-build:
    name: Build Island APK
    environment:
      java: 17
    scripts:
      - name: Setup Android SDK
        script: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0"
      - name: Clone deagle library
        script: |
          cd ..
          git clone https://github.com/oasisfeng/deagle.git
          cd island
      - name: Build APK
        script: ./gradlew :assembly:assembleCompleteRelease
    artifacts:
      - assembly/build/outputs/apk/complete/release/*.apk
